# Common Config Settings
BIT_LEN = 64 # 32
IO_PRE = "`FXP{}S_".format(BIT_LEN)
LSB_POW = -48 # -24
## PE
PE_ARRAY_DIM = 2
## EXP - POW 2
NUM_STAGE = 8
NUM_PASS = int(BIT_LEN/NUM_STAGE)-1
BIT_LEN_COMP = 9
GUARD_BIT = 0
BL_X = GUARD_BIT + ((BIT_LEN_COMP+NUM_STAGE-1) + NUM_PASS*NUM_STAGE)
BL_Y = GUARD_BIT + ((NUM_PASS+1)*NUM_STAGE + LSB_POW)
# Table
FILE_POW2 = f"table_pow2"